### ISSUE TITLE
aws.port need a integer default value

### ISSUE THREAD

**Issue by rach** [danjac/pyramid_storage#15]
With the current version if you don't set a port then you will get an

      TypeError: int() argument must be a string or a number, not 'NoneType'

This is due to the new connection options added:

https://github.com/danjac/pyramid_storage/blob/ecce44430a56cedf9aa967cbef4f2ff34f152a4f/pyramid_storage/s3.py#L72

**Comment by leplatrem** [comment]
This was supposed to be tested here:  https://github.com/danjac/pyramid_storage/blob/master/tests/test_s3.py#L232-L241

Indeed, none of the new options are supposed to be mandatory!
