### ISSUE TITLE
Configuring S3 pyramid_storage module - consistent key error

### ISSUE THREAD

**Issue by chuckbutler** [danjac/pyramid_storage#6]
I've attempted to configure the S3 flavor of the pyramid_storage module. I'm seeing consistent failures being raised, and I'm certain its due to how i've attempted to configure it. A doc update with a sample of how to configure the plugin would be helpful.

What I've attempted so far - in `development.ini` 

[storage]
aws.access_key='xxx'

storage.aws.access_key='xxx'
pyramid.storage.aws.access_key='xxx'

No matter how i format the setting, `KeyError: 'storage.aws.access_key' `

**Comment by danjac** [comment]
Do you have
    pyramid.includes =
        pyramid_storage.s3

In your configuration?

**Comment by chuckbutler** [comment]
I do not, I used the pyramid configurator approach, adding `config.include('pyramid_storage.sd')` in `__init__.py`

**Comment by danjac** [comment]
On Saturday 16 May 2015 11:48:08 Charles Butler wrote:
> I do not, I used the pyramid configurator approach, adding
> config.include('pyramid_storage.sd') in __init__.py

    config.include('pyramid_storage.sd')

Shouldn't that be config.include('pyramid_storage') ?

**Comment by danjac** [comment]
The settings have to go under **[app:main]**

    use = egg:sample_proj

    pyramid.reload_templates = true
    pyramid.debug_authorization = false
    pyramid.debug_notfound = false
    # etc
    storage.aws.access_key=my_key
    storage.aws.secret_key=my_secret
    storage.aws.bucket=my_bucket
